#!/bin/sh
#
# Start logging
#

[ -r /etc/default/uxas ] && . /etc/default/uxas

start() {
        printf "Starting OpenUxAS: "
        while [ ! -c /dev/uio0 ]; do echo "Waiting for /dev/uio0"; sleep 2; done;
        while [ ! -c /dev/uio1 ]; do echo "Waiting for /dev/uio1"; sleep 2; done;
        while [ ! -c /dev/uio2 ]; do echo "Waiting for /dev/uio2"; sleep 2; done;
        while [ ! -c /dev/uio3 ]; do echo "Waiting for /dev/uio3"; sleep 2; done;
        while [ ! -c /dev/uio4 ]; do echo "Waiting for /dev/uio4"; sleep 2; done;
        while [ ! -c /dev/uio5 ]; do echo "Waiting for /dev/uio5"; sleep 2; done;
        chgrp uxas /dev/uio0
        chgrp uxas /dev/uio1
        chgrp uxas /dev/uio2
        chgrp uxas /dev/uio3
        chgrp uxas /dev/uio4
        chgrp uxas /dev/uio5
        chmod g+rw /dev/uio0
        chmod g+rw /dev/uio1
        chmod g+rw /dev/uio2
        chmod g+rw /dev/uio3
        chmod g+rw /dev/uio4
        chmod g+rw /dev/uio5
        chmod +x /home/uxas/ex/p2/01_Waterway/runUxAS_WaterwaySearch_UAV.sh
        start-stop-daemon -b -S -q -m -p /var/run/uxas.pid -c uxas --exec /home/uxas/ex/p2/01_Waterway/runUxAS_WaterwaySearch_UAV.sh >> uxas-stdout
        echo "OK"
}

stop() {
        printf "Stopping OpenUxAS: "
        start-stop-daemon -K -q -p /var/run/uxas.pid
        echo "OK"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?

